routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth 路由
Auth::routes();
// ajax登录
Route::post('ajax/login', 'Auth\LoginController@ajaxLogin')->name('ajax.login');
// ajax重置密码
Route::post('ajax/password/email', 'Auth\ForgotPasswordController@ajaxSendResetLinkEmail')->name('ajax.password.email');
// ajax注册
Route::post('ajax/register', 'Auth\RegisterController@ajaxRegister')->name('ajax.register');

// Admin后台路由
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'check.permission']] ,function () {
    // 默认跳转首页
    Route::get('/', function () {
       return redirect()->route('admin.index');
    });

    // 后台入口
    Route::get('index', 'IndexController@index')->name('admin.index');

    // ajax获取二级菜单
    Route::get('getchildmenu', 'MenuTableController@ajaxGetChildMenu')->name('menutable.ajaxGetChild');
    // 缓存保存菜单排序
    Route::post('savemenuorder', 'MenuTableController@saveOrder')->name('menutable.saveMenuOrder');
    // 定制菜单,资源路由
    Route::resource('menutable', 'MenuTableController');
    // 图标参考
    Route::get('icon', 'IndexController@icon')->name('icon.index');
    // ajax获取用户列表
    Route::post('get_users', 'UserController@getUsers')->name('user.getUsers');
    // 用户,资源路由
    Route::resource('user', 'UserController');
    // 用户组,资源路由
    Route::resource('role', 'RoleController');
    // ajax获取权限列表
    Route::post('get_permissions', 'PermissionController@getPermissions')->name('permissions.getPermissions');
    // 权限,资源路由
    Route::resource('permissions', 'PermissionController');
    // 博客路由
    Route::post('article/get_articles', 'ArticleController@getArticles')->name('article.getArticles');
    Route::post('article/upload_image', "ArticleController@uploadImage")->name('article.uploadImage');
    Route::resource('article', 'ArticleController');
    // 博客文章分类
    Route::post('article_categories/save_order', 'ArticleCategoriesController@saveOrder')->name('article_categories.saveCateOrder');
    Route::resource('article_categories', 'ArticleCategoriesController');
    // 博客标签路由
    Route::post('article_tag/get_tags', 'ArticleTagController@getTags')->name('article_tag.getTags');
    Route::resource('article_tag', 'ArticleTagController');
    // 图片管理
    Route::get('picture', 'PictureController@index')->name('picture.index');
    Route::match(['get', 'post'], 'picture/upload', 'PictureController@uploadImage')->name('picture.upload');
    Route::delete('picture/{id}', 'PictureController@destroy')->name('picture.destroy');
    Route::post('picture/{id}/edit', 'PictureController@editFilename')->name('picture.edit');
    // 日志路由
    Route::get('log', 'LogViewerController@index')->name('log.index');
    Route::get('log/list', 'LogViewerController@listLogs')->name('log.list');
    Route::delete('log/delete', 'LogViewerController@delete')->name('log.destroy');
    Route::get('log/{date}', 'LogViewerController@show')->name('log.show');
    Route::get('log/{date}/download', 'LogViewerController@download')->name('log.download');
    Route::get('log/{date}/{level}', 'LogViewerController@showByLevel')->name('log.filter');
    // 系统设置
    Route::get('setting/{mode?}', 'SettingController@index')->name('setting.index');
    Route::put('setting/{id}', 'SettingController@saveSet')->name('setting.update');
});

//
Route::group(['prefix' => 'member', 'namespace' => 'Member', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return redirect('member/index');
    });
    // 会员中心
    Route::get('index', 'MemberController@index')->name('member.index');
    // 资料编辑
    Route::get('edit', 'MemberController@edit')->name('member.edit');
    // 资料编辑保存
    Route::post('edit', 'MemberController@editStore')->name('member.edit');
    // 重置密码
    Route::get('password', 'MemberController@password')->name('member.password');
    // 重置密码保存
    Route::post('password', 'MemberController@passwordStore')->name('member.password');
});

app/Models/Article.php
<?php

namespace App\Models;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Article extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [];

    /*
     * 多对多关联分类表
     * */
    public function categories()
    {
        return $this->belongsToMany('App\Models\ArticleCategory', 'article_cate')->using('App\Models\ArticleCate');
    }

    /*
   * 多对多关联标签表
   * */
    public function tags()
    {
        return $this->belongsToMany('App\Models\ArticleTag', 'article_tag');
    }

    /**
     * 检查文章是否属于该分类
     * @param $category_id int 分类ID
     * @return bool
     * */
    public function hasCategory($category_id)
    {
        $result = $this->categories()->where('article_category_id', $category_id)->first();
        if (empty($result)) {
            return false;
        }
        return true;
    }

    /**
     * 检查文章是否有此标签
     * @param $tag_id int 标签ID
     * @return bool
     * */
    public function hasTag($tag_id)
    {
        $result = $this->tags()->where('article_tag_id', $tag_id)->first();
        if (empty($result)) {
            return false;
        }
        return true;
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\Eloquent\ArticleRepositoryEloquent;
use App\Http\Requests\ArticlePost;
use Auth;
use App\Services\ImageUpload;
use App\Repositories\Eloquent\ImageRepositoryEloquent;
use App\Services\ArticleCateTag;
use Illuminate\Http\Request;
use DataTables;
use Storage;

class ArticleController extends Controller
{
    protected $articleRepositoryEloquent;

    protected $imageUpload;

    protected $imageRepositoryEloquent;

    protected $articleCateTag;

    public function __construct(ArticleRepositoryEloquent $articleRepositoryEloquent, ImageUpload $imageUpload, ImageRepositoryEloquent $imageRepositoryEloquent, ArticleCateTag $articleCateTag)
    {
        $this->articleRepositoryEloquent = $articleRepositoryEloquent;
        $this->imageUpload = $imageUpload;
        $this->imageRepositoryEloquent = $imageRepositoryEloquent;
        $this->articleCateTag = $articleCateTag;
    }
    /**
     * 文章列表
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.article.index');
    }

    /**
     * 创建文章
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 读取全部分类和标签
        $data = $this->articleCateTag->getAllCateTag();
        return view('admin.article.create', ['cates' => $data['cates'], 'tags' => $data['tags'], 'is_edit' => false]);
    }

    /**
     * 保存文章
     *
     * @param  \App\Http\Requests\ArticlePost
     * @return \Illuminate\Http\Response
     */
    public function store(ArticlePost $request)
    {
        $article_info = $request;
        // 获取发布人信息
        $article_info->user_id = Auth::user()->id;
        $article_info->author = Auth::user()->name;
        // 上传图片
        if ($request->hasFile('article_image')) {
            $upload_status = $this->imageUpload->uploadImage($request->file('article_image'));
            $file_arr = $upload_status['filename'];
            // 保存到图片表
            $insert_id = $this->saveImageInfo($file_arr);
            $article_info->article_image = $file_arr['small'];
        }
        // 保存文章，分类，标签
        $result = $this->articleCateTag->saveArticle($article_info);
        if ($result) {
            return redirect()->route('article.index');
        }
    }

    /**
     * 保存图片信息到数据库
     * @param $file_arr array
     * @return string 插入ID
     * */
    protected function saveImageInfo($file_arr)
    {
        $insert_id = $this->imageRepositoryEloquent->saveImage($file_arr, Auth::user());
        return $insert_id;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $article = $this->articleCateTag->getArticleInfo($id);
        // 读取文章分类
        $data = $this->articleCateTag->getAllCateTag();
        return view('admin.article.create', ['cates' => $data['cates'], 'tags' => $data['tags'], 'article' => $article, 'is_edit' => true]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ArticlePost
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticlePost $request, $id)
    {
        $article_info = $request;
        // 上传图片
        if ($request->hasFile('article_image')) {
            $upload_status = $this->imageUpload->uploadImage($request->file('article_image'));
            $file_arr = $upload_status['filename'];
            // 保存到图片表
            $insert_id = $this->saveImageInfo($file_arr);
            $article_info->article_image = $file_arr['small'];
        }
        $result = $this->articleCateTag->updateArticle($id, $article_info);
        if ($result) {
            return redirect()->route('article.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->articleCateTag->deleteArticle($id);
        if ($result) {
            return response()->json(['state' => 'success']);
        }
    }

    /*
     * ajax获取文章列表
     * */
    public function getArticles()
    {
        $articles = $this->articleRepositoryEloquent->all();
        $datatables_json = Datatables::of($articles)
        ->addColumn('action', function ($article){
        $edit_url = route('article.edit', $article->id);
        $delete_url = route('article.destroy', $article->id);
        return <<<Eof
                <a href="javascript:;" class="btn btn-outline dark btn-sm black mt-sweetalert"
                                                            style="margin-bottom: 0;"
                                                           data-title="确定要删除该文章吗？"
                                                           data-message="（文章中的图片请在媒体库删除）"
                                                           data-type="warning"
                                                           data-allow-outside-click="true"
                                                           data-show-cancel-button="true"
                                                           data-cancel-button-text="点错了"
                                                           data-cancel-button-class="btn-danger"
                                                           data-show-confirm-button="true"
                                                           data-confirm-button-text="确定"
                                                           data-confirm-button-class="btn-info"
                                                           data-popup-title-success="删除成功"
                                                           data-close-on-cancel="true"
                                                           data-close-on-confirm="false"
                                                           data-show-loader-on-confirm="true"
                                                           data-ajax-url="{$delete_url}"
                                                           data-remove-dom="article_li_"
                                                           data-id="{$article->id}"
                                                        >
                                                            <i class="fa fa-trash-o"></i>
                                                            删除
                                                        </a>
                                                        <a href="{$edit_url}" class="btn btn-outline green btn-sm purple"><i class="fa fa-edit"></i>编辑</a>
Eof;
    })
        ->addColumn('cate', function ($article) {
            $categories = '';
            if(!empty($article->categories)) {
                foreach($article->categories as $key => $cate) {
                    $categories .= '<span class="label label-sm label-info">' .htmlspecialchars($cate->name) . '</span>&nbsp;';
                }
            } else {
                $categories =  '<span class="label label-sm label-warning">未分类</span>';
            }
            return $categories;
        })
        ->rawColumns(['cate', 'action'])
        ->setRowId(function ($article) {
            return 'article_li_'.$article->id;
        })
        ->make(true);
        return $datatables_json;
    }
    
    /**
     * MKDown 图片上传
     * @param $request Request 上传请求
     * @return mixed
     * */
    public function uploadImage(Request $request)
    {
        $json = [
            'filename' => '',
            'success' => 0,
            'message' => '失败',
            'url' => '',
        ];
        // 上传图片
        if ($request->hasFile('editormd-image-file')) {
            $upload_status = $this->imageUpload->uploadImage($request->file('editormd-image-file'));
            $file_arr = $upload_status['filename'];
            // 保存到图片表
            $insert_id = $this->saveImageInfo($file_arr);
            $realpayh = env('APP_URL').Storage::url($file_arr['original']);
            $json = array_replace($json, ['success' => 1, 'url' => $realpayh, 'message' => '上传成功', 'filename' => $realpayh]);
        }
        return response()->json($json);
    }
}

resources/views/admin/article/create.blade.php
@extends('admin.layouts.main')

{{--顶部前端资源--}}
@section('styles')
    <link href="{{ asset('vendor/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/select2/css/select2-bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet" type="text/css" />
    {!! editor_css() !!}
@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <div class="col-md-8 ">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-red-sunglo">
                        <i class="icon-settings font-red-sunglo"></i>
                        <span class="caption-subject bold uppercase"> 文章发布 </span>
                    </div>
                    <div class="actions">
                        <div class="btn-group">
                            <a class="btn btn-sm green dropdown-toggle" href="javascript:;" data-toggle="dropdown"> Actions
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-pencil"></i> Edit </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-trash-o"></i> Delete </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-ban"></i> Ban </a>
                                </li>
                                <li class="divider"> </li>
                                <li>
                                    <a href="javascript:;"> Make admin </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form role="form" enctype="multipart/form-data" method="post" action="@if($is_edit){{ route('article.update', [$article->id]) }}@else{{ route('article.store') }}@endif">
                        {{ csrf_field() }}
                        @if($is_edit)
                            <input type="hidden" name="_method" value="PUT">
                        @endif
                        <div class="form-body">
                            <div class="form-group @if($errors->has('title')) has-error @endif">
                                <label>文章标题</label>
                                <div class="input-icon">
                                    <i class="fa fa-keyboard-o font-green"></i>
                                    <input type="text" class="form-control" name="title" placeholder="文章标题"
                                           value="{{ $is_edit ? $article->title : old('title') }}"
                                    >
                                    @if($errors->has('title'))
                                        <span class="help-block">{{ $errors->first('title') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="multiple" class="control-label">文章分类</label>
                                <select id="multiple" class="form-control select2-multiple" multiple name="cates[]">
                                    @if(!empty($cates))
                                        @foreach($cates as $cate)

                                                <option value="{{ $cate->id }}"  @if($is_edit) {{ $article->hasCategory($cate->id) ? 'selected' : ''}} @endif>{{ $cate->name }}</option>
                                                @if(!empty($cate->child))
                                                    @foreach($cate->child as $item)
                                                    <option value="{{ $item->id }}" @if($is_edit) {{ $article->hasCategory($item->id) ? 'selected' : ''}} @endif>&nbsp;&nbsp;{{ $item->name }}</option>
                                                    @endforeach
                                                @endif

                                        @endforeach
                                    @else
                                        <optgroup label="未分类">
                                            <option value="0" disabled="disabled">请创建分类</option>
                                        </optgroup>
                                    @endif
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label">文章标签</label>
                                <div class="">
                                    <select class="bs-select form-control" name="tags[]" data-live-search="true" data-size="8" multiple>
                                        @if(!empty($tags))
                                            @foreach($tags as $tag)
                                                <option value="{{ $tag->id }}" @if($is_edit){{ $article->hasTag($tag->id)? 'selected ': '' }}@endif>{{ $tag->name }}</option>
                                            @endforeach
                                        @else
                                            <option>无标签</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="form-group @if($errors->has('abstract')) has-error @endif">
                                <label>摘要</label>
                                <textarea class="form-control" name="abstract" rows="3">{{ $is_edit ? $article->abstract : old('abstract') }}</textarea>
                                @if($errors->has('abstract'))
                                    <span class="help-block">{{ $errors->first('abstract') }}</span>
                                @endif
                            </div>
                            <div class="form-group last">
                                <label class="control-label">文章特色图像</label>
                                <div class="">
                                    <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                            <img src="@if($is_edit){{ $article->article_image ?: asset('assets/admin/img/no_image.png') }}@else{{ asset('assets/admin/img/no_image.png') }}@endif" alt="" /> </div>
                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                        <div>
                                            <span class="btn default btn-file">
                                                <span class="fileinput-new"> 选择图片 </span>
                                                <span class="fileinput-exists"> 更换 </span>
                                                <input type="file" name="article_image">
                                            </span>
                                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> 删除 </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group @if($errors->has('editormd-html-code')) has-error @endif">
                                <label>正文</label>
                                <div id="editormd">
                                    <textarea style="" id="article_content">{{ $is_edit ? $article->content_md : old('editormd-markdown-doc') }}</textarea>
                                </div>
                                @if($errors->has('editormd-html-code'))
                                    <span class="help-block">{{ $errors->first('editormd-html-code') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">发布</button>
                            <button type="button" class="btn default">取消</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')
    <script src="{{ asset('vendor/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/select2/js/select2.full.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/layouts/scripts/components-select2.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/bootstrap-select/js/bootstrap-select.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/layouts/scripts/components-bootstrap-select.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/InlineAttachment/src/inline-attachment.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/InlineAttachment/src/jquery.inline-attachment.js') }}" type="text/javascript"></script>
    {{-- Md编辑器 --}}
    {!! editor_js_a() !!}
    <script type="text/javascript">
        // 拖拽上传
        var inlineAttachmentOptions = {
            uploadUrl: '{{ route('article.uploadImage') }}',
            uploadFieldName: 'editormd-image-file',
            progressText: '![正在上传文件...]()',
            urlText: "\n ![file]({filename}) \n\n",
            extraParams: {
                "_token": '{{ csrf_token() }}'
            }
        };
        $('textarea').inlineattachment(inlineAttachmentOptions);
        // MKDown 编辑器
        $(function() {
            var editor = editormd("editormd");
        });

    </script>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.main')

{{--顶部前端资源--}}
@section('styles')
    <link href="{{ asset('vendor/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    {{--ajax使用--}}
    <link href="{{ asset('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-red"></i>
                        <span class="caption-subject font-red sbold uppercase">文章列表</span>
                    </div>
                    <div class="actions">
                        <div class="btn-group">
                            <a href="{{ route('article.create') }}" class="btn green btn-outline">
                                <i class="fa fa-edit"></i>
                                发布文章
                            </a>
                        </div>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                            <thead>
                            <tr role="row" class="heading">
                                <th > ID </th>
                                <th > 文章标题 </th>
                                <th > 作者 </th>
                                <th > 分类 </th>
                                <th > 添加时间 </th>
                                <th > 修改时间 </th>
                                <th > 操作 </th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')
    <script type="text/javascript">
        var ajax_url = "{{ route('article.getArticles') }}";
    </script>
    <script src="{{asset('assets/admin/layouts/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('vendor/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('vendor/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
    {{--ajax使用--}}
    <script src="{{asset('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
    {{--datatables操作插件--}}
    <script src="{{asset('assets/admin/articles/scripts/datatables-articles.js')}}" type="text/javascript"></script>
    {{--sweetalert弹窗--}}
    <script src="{{asset('assets/admin/layouts/scripts/sweetalert/sweetalert-ajax-delete.js')}}" type="text/javascript"></script>
@endsection