routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth 路由
Auth::routes();
// ajax登录
Route::post('ajax/login', 'Auth\LoginController@ajaxLogin')->name('ajax.login');
// ajax重置密码
Route::post('ajax/password/email', 'Auth\ForgotPasswordController@ajaxSendResetLinkEmail')->name('ajax.password.email');
// ajax注册
Route::post('ajax/register', 'Auth\RegisterController@ajaxRegister')->name('ajax.register');

// Admin后台路由
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'check.permission']] ,function () {
    // 默认跳转首页
    Route::get('/', function () {
       return redirect()->route('admin.index');
    });

    // 后台入口
    Route::get('index', 'IndexController@index')->name('admin.index');

    // ajax获取二级菜单
    Route::get('getchildmenu', 'MenuTableController@ajaxGetChildMenu')->name('menutable.ajaxGetChild');
    // 缓存保存菜单排序
    Route::post('savemenuorder', 'MenuTableController@saveOrder')->name('menutable.saveMenuOrder');
    // 定制菜单,资源路由
    Route::resource('menutable', 'MenuTableController');
    // 图标参考
    Route::get('icon', 'IndexController@icon')->name('icon.index');
    // ajax获取用户列表
    Route::post('get_users', 'UserController@getUsers')->name('user.getUsers');
    // 用户,资源路由
    Route::resource('user', 'UserController');
    // 用户组,资源路由
    Route::resource('role', 'RoleController');
    // ajax获取权限列表
    Route::post('get_permissions', 'PermissionController@getPermissions')->name('permissions.getPermissions');
    // 权限,资源路由
    Route::resource('permissions', 'PermissionController');
    // 博客路由
    Route::post('article/get_articles', 'ArticleController@getArticles')->name('article.getArticles');
    Route::post('article/upload_image', "ArticleController@uploadImage")->name('article.uploadImage');
    Route::resource('article', 'ArticleController');
    // 博客文章分类
    Route::post('article_categories/save_order', 'ArticleCategoriesController@saveOrder')->name('article_categories.saveCateOrder');
    Route::resource('article_categories', 'ArticleCategoriesController');
    // 博客标签路由
    Route::post('article_tag/get_tags', 'ArticleTagController@getTags')->name('article_tag.getTags');
    Route::resource('article_tag', 'ArticleTagController');
    // 图片管理
    Route::get('picture', 'PictureController@index')->name('picture.index');
    Route::match(['get', 'post'], 'picture/upload', 'PictureController@uploadImage')->name('picture.upload');
    Route::delete('picture/{id}', 'PictureController@destroy')->name('picture.destroy');
    Route::post('picture/{id}/edit', 'PictureController@editFilename')->name('picture.edit');
    // 日志路由
    Route::get('log', 'LogViewerController@index')->name('log.index');
    Route::get('log/list', 'LogViewerController@listLogs')->name('log.list');
    Route::delete('log/delete', 'LogViewerController@delete')->name('log.destroy');
    Route::get('log/{date}', 'LogViewerController@show')->name('log.show');
    Route::get('log/{date}/download', 'LogViewerController@download')->name('log.download');
    Route::get('log/{date}/{level}', 'LogViewerController@showByLevel')->name('log.filter');
    // 系统设置
    Route::get('setting/{mode?}', 'SettingController@index')->name('setting.index');
    Route::put('setting/{id}', 'SettingController@saveSet')->name('setting.update');
});

//
Route::group(['prefix' => 'member', 'namespace' => 'Member', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return redirect('member/index');
    });
    // 会员中心
    Route::get('index', 'MemberController@index')->name('member.index');
    // 资料编辑
    Route::get('edit', 'MemberController@edit')->name('member.edit');
    // 资料编辑保存
    Route::post('edit', 'MemberController@editStore')->name('member.edit');
    // 重置密码
    Route::get('password', 'MemberController@password')->name('member.password');
    // 重置密码保存
    Route::post('password', 'MemberController@passwordStore')->name('member.password');
});

app/Models/ArticleTag.php
<?php

namespace App\Models;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class ArticleTag extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [];

    /*
    * 多对多关联文章表
    * */
    public function articles()
    {
        return $this->belongsToMany('App\Models\Article', 'article_tag');
    }

}

app/Http/Controllers/Admin/ArticleTagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Eloquent\ArticleTagRepositoryEloquent;
use DataTables;
use App\Services\ArticleCateTag;

class ArticleTagController extends Controller
{
    protected $articleTagRepositoryEloquent;

    protected $articleCateTag;

    public function __construct(ArticleTagRepositoryEloquent $articleTagRepositoryEloquent, ArticleCateTag $articleCateTag)
    {
        $this->articleTagRepositoryEloquent = $articleTagRepositoryEloquent;
        $this->articleCateTag = $articleCateTag;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.article_tags.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(
            $request,
            [
                'name' => 'required',
                'display_name' => 'allow_letter'
            ],
            [
                'name.required' => '请填写标签名',
                'display_name.allow_letter' => '英文别名只能是字母或\'-\',\' _\'',
            ]
        );
        $result = $this->articleTagRepositoryEloquent->saveTag($request);
        if ($result) {
            $data = [
                'code' => 0,
                'message' => '添加成功'
            ];
        } else {
            $data = [
                'code' => 1,
                'message' => '添加失败'
            ];
        }
        return response()->json($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = $this->articleTagRepositoryEloquent->find($id);
        $data = [
            'code' => 0,
            'data' => [
                'tag' => $tag
            ]
        ];
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'name' => 'required',
                'display_name' => 'allow_letter'
            ],
            [
                'name.required' => '请填写标签名',
                'display_name.allow_letter' => '英文别名只能是字母或\'-\',\' _\'',
            ]
        );
        $result = $this->articleTagRepositoryEloquent->updateTag($id, $request);
        if ($result) {
            $data = [
                'code' => 0,
                'message' => '修改成功'
            ];
        } else {
            $data = [
                'code' => 1,
                'message' => '修改失败'
            ];
        }
        return response()->json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->articleCateTag->deleteTag($id);
        if ($result) {
            return response()->json(['state' => 'success']);
        }
    }

    /*
     * ajax获取列表
     * */
    public function getTags()
    {
        $tags = $this->articleTagRepositoryEloquent->all();
        $datatables_json = Datatables::of($tags)
            ->addColumn('action', function ($tag){
                $edit_url = route('article_tag.edit', $tag->id);
                $delete_url = route('article_tag.destroy', $tag->id);
                return <<<Eof
                <a href="javascript:;" class="btn btn-outline dark btn-sm black mt-sweetalert"
                                                            style="margin-bottom: 0;"
                                                           data-title="确定要删除该文章吗？"
                                                           data-message="（文章中的图片请在媒体库删除）"
                                                           data-type="warning"
                                                           data-allow-outside-click="true"
                                                           data-show-cancel-button="true"
                                                           data-cancel-button-text="点错了"
                                                           data-cancel-button-class="btn-danger"
                                                           data-show-confirm-button="true"
                                                           data-confirm-button-text="确定"
                                                           data-confirm-button-class="btn-info"
                                                           data-popup-title-success="删除成功"
                                                           data-close-on-cancel="true"
                                                           data-close-on-confirm="false"
                                                           data-show-loader-on-confirm="true"
                                                           data-ajax-url="{$delete_url}"
                                                           data-remove-dom="tag_li_"
                                                           data-id="{$tag->id}"
                                                        >
                                                            <i class="fa fa-trash-o"></i>
                                                            删除
                                                        </a>
                                                        <a href="javascript:;" onclick="getTag({$tag->id})" class="btn btn-outline green btn-sm purple"><i class="fa fa-edit"></i>编辑</a>
Eof;
            })
            ->rawColumns(['action'])
            ->setRowId(function ($tag) {
                return 'tag_li_'.$tag->id;
            })
            ->make(true);
        return $datatables_json;
    }
}

resources/views/admin/article_tags/index.blade.php
@extends('admin.layouts.main')

{{--顶部前端资源--}}
@section('styles')
    <link href="{{ asset('vendor/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    {{--ajax使用--}}
    <link href="{{ asset('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet" type="text/css" />
    <style>
        /*.p-margin-top p{ margin: 10px 0px 10px 0px; }*/
    </style>
@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-red"></i>
                        <span class="caption-subject font-red sbold uppercase">标签列表</span>
                    </div>
                    <div class="actions">
                        <div class="btn-group">
                            <a href='javascript:;' class="btn green btn-outline" onclick="addTag()">
                                <i class="fa fa-edit"></i>
                                添加标签
                            </a>
                        </div>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                            <thead>
                            <tr role="row" class="heading">
                                <th > ID </th>
                                <th > 标签名称 </th>
                                <th > 标签别名 </th>
                                <th > 添加时间 </th>
                                <th > 修改时间 </th>
                                <th > 操作 </th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- 添加标签 --}}
    <div id="tag_add" class="modal fade" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">添加标签</h4>
                </div>
                <div class="modal-body">
                    <div class="scroller" style="height:200px" data-always-visible="1" data-rail-visible1="1">
                        <div class="col-md-12">
                            <input type="hidden" id="tag_id" name="tag_id">
                            <div class="" id="name_error">
                                <p>
                                    <input class="form-control" type="text" id="tag_name" placeholder="标签名">
                                </p>
                            </div>
                            <div class="" id="display_name_error">
                                <p>
                                    <input class="form-control" type="text" id="tag_display_name" placeholder="英文别名(只能是字母)">
                                </p>
                            </div>
                            <p class="alert alert-danger" style="display: none" id="tag_error">
                                <strong>错误!</strong>&nbsp;&nbsp;<span id="post-error"></span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn dark btn-outline">关闭</button>
                    <button type="button" class="btn green" href="javascript:;" onclick="choose()">保存</button>
                </div>
            </div>
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')
    <script type="text/javascript">
        var ajax_url = "{{ route('article_tag.getTags') }}";
        var store_url = "{{ route("article_tag.store") }}";
    </script>
    <script src="{{asset('assets/admin/layouts/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('vendor/datatables/datatables.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('vendor/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
    {{--ajax使用--}}
    <script src="{{asset('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
    {{--datatables操作插件--}}
    <script src="{{asset('assets/admin/article_tags/scripts/datatables-tags.js')}}" type="text/javascript"></script>
    {{--sweetalert弹窗--}}
    <script src="{{asset('assets/admin/layouts/scripts/sweetalert/sweetalert-ajax-delete.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/admin/article_tags/scripts/article-tags.js')}}" type="text/javascript"></script>
@endsection