routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth 路由
Auth::routes();
// ajax登录
Route::post('ajax/login', 'Auth\LoginController@ajaxLogin')->name('ajax.login');
// ajax重置密码
Route::post('ajax/password/email', 'Auth\ForgotPasswordController@ajaxSendResetLinkEmail')->name('ajax.password.email');
// ajax注册
Route::post('ajax/register', 'Auth\RegisterController@ajaxRegister')->name('ajax.register');

// Admin后台路由
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'check.permission']] ,function () {
    // 默认跳转首页
    Route::get('/', function () {
       return redirect()->route('admin.index');
    });

    // 后台入口
    Route::get('index', 'IndexController@index')->name('admin.index');

    // ajax获取二级菜单
    Route::get('getchildmenu', 'MenuTableController@ajaxGetChildMenu')->name('menutable.ajaxGetChild');
    // 缓存保存菜单排序
    Route::post('savemenuorder', 'MenuTableController@saveOrder')->name('menutable.saveMenuOrder');
    // 定制菜单,资源路由
    Route::resource('menutable', 'MenuTableController');
    // 图标参考
    Route::get('icon', 'IndexController@icon')->name('icon.index');
    // ajax获取用户列表
    Route::post('get_users', 'UserController@getUsers')->name('user.getUsers');
    // 用户,资源路由
    Route::resource('user', 'UserController');
    // 用户组,资源路由
    Route::resource('role', 'RoleController');
    // ajax获取权限列表
    Route::post('get_permissions', 'PermissionController@getPermissions')->name('permissions.getPermissions');
    // 权限,资源路由
    Route::resource('permissions', 'PermissionController');
    // 博客路由
    Route::post('article/get_articles', 'ArticleController@getArticles')->name('article.getArticles');
    Route::post('article/upload_image', "ArticleController@uploadImage")->name('article.uploadImage');
    Route::resource('article', 'ArticleController');
    // 博客文章分类
    Route::post('article_categories/save_order', 'ArticleCategoriesController@saveOrder')->name('article_categories.saveCateOrder');
    Route::resource('article_categories', 'ArticleCategoriesController');
    // 博客标签路由
    Route::post('article_tag/get_tags', 'ArticleTagController@getTags')->name('article_tag.getTags');
    Route::resource('article_tag', 'ArticleTagController');
    // 图片管理
    Route::get('picture', 'PictureController@index')->name('picture.index');
    Route::match(['get', 'post'], 'picture/upload', 'PictureController@uploadImage')->name('picture.upload');
    Route::delete('picture/{id}', 'PictureController@destroy')->name('picture.destroy');
    Route::post('picture/{id}/edit', 'PictureController@editFilename')->name('picture.edit');
    // 日志路由
    Route::get('log', 'LogViewerController@index')->name('log.index');
    Route::get('log/list', 'LogViewerController@listLogs')->name('log.list');
    Route::delete('log/delete', 'LogViewerController@delete')->name('log.destroy');
    Route::get('log/{date}', 'LogViewerController@show')->name('log.show');
    Route::get('log/{date}/download', 'LogViewerController@download')->name('log.download');
    Route::get('log/{date}/{level}', 'LogViewerController@showByLevel')->name('log.filter');
    // 系统设置
    Route::get('setting/{mode?}', 'SettingController@index')->name('setting.index');
    Route::put('setting/{id}', 'SettingController@saveSet')->name('setting.update');
});

//
Route::group(['prefix' => 'member', 'namespace' => 'Member', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return redirect('member/index');
    });
    // 会员中心
    Route::get('index', 'MemberController@index')->name('member.index');
    // 资料编辑
    Route::get('edit', 'MemberController@edit')->name('member.edit');
    // 资料编辑保存
    Route::post('edit', 'MemberController@editStore')->name('member.edit');
    // 重置密码
    Route::get('password', 'MemberController@password')->name('member.password');
    // 重置密码保存
    Route::post('password', 'MemberController@passwordStore')->name('member.password');
});

app/Models/Menu.php
<?php

namespace App\Models;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Menu extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = ['parent_id', 'order', 'name', 'icon', 'uri', 'permission_name'];

}

resources/views/admin/menu/menu_add.blade.php
<div class="portlet light bordered formBox" id="createBox">
    <div class="portlet-title">
        <div class="caption font-green">
            <i class="icon-pin font-green"></i>
            <span class="caption-subject bold uppercase">添加菜单</span>
        </div>
        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>信息填写出错!</strong>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
        @endif
        <form role="form" id="createForm" action="{{ route("menutable.store") }}">
            {{ csrf_field() }}
            <div class="form-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input form-md-floating-label ">
                            <select class="form-control edited " id="form_parent_menu_1" name="parent_id_1">
                                <option value="0" selected>顶级菜单</option>
                                @if(!empty($menu_first))
                                    @foreach($menu_first as $menu)
                                        <option value="{{ $menu->id }}">{{ $menu->name }}</option>
                                    @endforeach
                                @endif
                            </select>
                            <label for="form_parent_menu_1">一级菜单</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input form-md-floating-label ">
                            <select class="form-control edited " id="form_parent_menu_2" name="parent_id_2">
                                <option value="0" selected>无二级菜单</option>
                            </select>
                            <label for="form_parent_menu_1">二级菜单</label>
                        </div>
                    </div>
                </div>
                <div class="form-group form-md-line-input form-md-floating-label
                <?php if ($errors->has('name')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_name" name="name" value="{{ old('name') }}">
                    <label for="form_name">名称</label>
                    <span class="help-block">菜单名称</span>
                </div>
                <div class="form-group form-md-line-input form-md-floating-label
                <?php if ($errors->has('icon')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_icon" name="icon" value="{{ old('icon') }}">
                    <label for="form_icon">图标</label>
                    <span class="help-block">字体图标代码(完整class名称支持 Fontawesome Icons，Simple Line Icons，Glyphicons)</span>
                </div>
                <div class="form-group form-md-line-input form-md-floating-label
                <?php if ($errors->has('uri')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_uri" name="uri" value="{{ old('uri') }}">
                    <label for="form_uri">路径名称</label>
                    <span class="help-block">路由文件中设置的路由名称</span>
                </div>
            </div>
            <div class="form-actions noborder">
                <button type="submit" class="btn green createButton" >创建菜单</button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $('#form_parent_menu_1').change(function () {
        var id = $('#form_parent_menu_1').val();
        var url = "{{ route('menutable.ajaxGetChild') }}";
        //先清空下拉列表
        $('#form_parent_menu_2').empty();
        $('#form_parent_menu_2').append("<option value='0' selected>无二级菜单</option>");
        //重新获取下拉列表
        $.getJSON(
                url,
                {parent_id:id},
                function (data) {
                    if (data != []) {
                        var html = '';
                        $(data).each(function (index, element) {
                            html += "<option value='"+element.id+"'>"+element.name+"</option>"
                        });
                        $('#form_parent_menu_2').append(html);
                    }

                }
        );

    });
</script>

resources/views/admin/menu/menu_edit.blade.php
<div class="portlet light bordered formBox" id="editBox">
    <div class="portlet-title">
        <div class="caption font-green">
            <i class="icon-pin font-green"></i>
            <span class="caption-subject bold uppercase">编辑菜单</span>
        </div>
        <div class="actions">
            <a class="btn btn-circle btn-icon-only btn-default close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>信息填写出错!</strong>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
        @endif
        <form role="form" method="post" action="{{ route("menutable.update", $menu_info->id) }}" id="editForm">
            <input type="hidden" name="_method" value="PUT">
            {{ csrf_field() }}
            <input type="hidden" name="id" value="{{ $menu_info->id }}">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input has-success">
                            <input type="text" class="form-control" disabled="" id="form_control_1" value="{{ $menu_info->created_at }}">
                            <label for="form_control_1">创建时间</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input has-warning">
                            <input type="text" class="form-control" disabled="" id="form_control_1" value="{{ $menu_info->updated_at }}">
                            <label for="form_control_1">更新时间</label>
                        </div>
                    </div>
                </div>
                <div class="form-group form-md-line-input
                <?php if ($errors->has('name')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_name" name="name" value="{{ $menu_info->name }}">
                    <label for="form_name">名称</label>
                    <span class="help-block">菜单名称</span>
                </div>
                <div class="form-group form-md-line-input
                <?php if ($errors->has('icon')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_icon" name="icon" value="{{ $menu_info->icon }}">
                    <label for="form_icon">图标</label>
                    <span class="help-block">字体图标代码(完整class名称支持 Fontawesome Icons，Simple Line Icons，Glyphicons)</span>
                </div>
                <div class="form-group form-md-line-input
                <?php if ($errors->has('uri')) { echo "has-error"; } ?>">
                    <input type="text" class="form-control" id="form_uri" name="uri" value="{{ $menu_info->uri }}">
                    <label for="form_uri">路径名称</label>
                    <span class="help-block">路由文件中设置的路由名称</span>
                </div>
            </div>
            <div class="form-actions noborder">
                <button type="submit" class="btn blue editButton" >更新菜单</button>
            </div>
        </form>
    </div>
</div>

resources/views/admin/menu/menu_table.blade.php
@extends('admin.layouts.main')
@inject('MenuPresenter', 'App\Presenters\Admin\MenuPresenter')
{{--顶部前端资源--}}
@section('styles')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{ asset('vendor/jquery-nestable/jquery.nestable.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('vendor/ladda/ladda-themeless.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <style type="text/css">
        .menu-option {
            float: right;
        }
        .menu-option i {
            margin: 0px 5px;
        }
    </style>
@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <input type="hidden" id="nestable_list_1_output">
        <div class="col-md-6">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-list font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">菜单列表</span>
                    </div>
                    <div class="actions">
                        <div class="btn-group">
                        <button type="button" class="btn purple mt-ladda-btn ladda-button btn-outline btn-circle" data-style="slide-left" data-spinner-color="#333" id="menu-save">
                            <span class="ladda-label">保存排序</span>
                            <span class="ladda-spinner"></span>
                        </button>
                        </div>
                    </div>
                </div>
                <div class="portlet-body ">
                    <div class="dd" id="nestable_list_1">
                        @if(!empty($menus))
                            {!! $MenuPresenter->menuOrderList($menus) !!}
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 add_menu_html">
            <div class="text-center middle-box" style="margin-top: 150px">
                <h4 style="color: #555"> 在这里添加或者编辑菜单内容 </h4>
                <button type="button" class="btn btn-success mt-ladda-btn ladda-button create_menu"
                        data-style="expand-up" data-href="{{ route("menutable.create") }}">
                    <span class="ladda-label">
                        <i class="fa fa-plus"></i> 添加菜单
                    </span>
                    <span class="ladda-spinner"></span>
                </button>
            </div>
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ asset('vendor/jquery-nestable/jquery.nestable.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/admin/menu/scripts/ui-nestable.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/ladda/spin.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/ladda/ladda.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/admin/menu/scripts/ui-buttons.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/admin/menu/scripts/menu.js') }}" type="text/javascript"></script>
{{--sweetalert弹窗--}}
<script src="{{ asset('assets/admin/layouts/scripts/sweetalert/sweetalert-ajax-delete.js') }}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        SweetAlert.init();
    });
    var cache_url = "{{ route('menutable.saveMenuOrder') }}";
    //保存排序
    $('#menu-save').on('click' ,function () {
        var menu = $('#nestable_list_1_output').val();
        var settings = {
            type: "POST",
            url: cache_url,
            data: {menu: menu},
            dataType:"json",
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(data) {
                sweetAlert({
                    title:"保存成功",
                    type:"success"
                });
            },
            error:function (xhr, errorText, errorType) {
                if (xhr.responseJSON.error == 'no_permissions') {
                    sweetAlert({
                        title:'您没有此权限',
                        text:"请联系管理员",
                        type:"error"
                    });
                    return false;
                } else {
                    sweetAlert({
                        title:'未知错误',
                        text:"请联系管理员",
                        type:"error"
                    });
                    return false;
                }
            }
        };
        $.ajax(settings)
    });
</script>
@endsection