routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth 路由
Auth::routes();
// ajax登录
Route::post('ajax/login', 'Auth\LoginController@ajaxLogin')->name('ajax.login');
// ajax重置密码
Route::post('ajax/password/email', 'Auth\ForgotPasswordController@ajaxSendResetLinkEmail')->name('ajax.password.email');
// ajax注册
Route::post('ajax/register', 'Auth\RegisterController@ajaxRegister')->name('ajax.register');

// Admin后台路由
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'check.permission']] ,function () {
    // 默认跳转首页
    Route::get('/', function () {
       return redirect()->route('admin.index');
    });

    // 后台入口
    Route::get('index', 'IndexController@index')->name('admin.index');

    // ajax获取二级菜单
    Route::get('getchildmenu', 'MenuTableController@ajaxGetChildMenu')->name('menutable.ajaxGetChild');
    // 缓存保存菜单排序
    Route::post('savemenuorder', 'MenuTableController@saveOrder')->name('menutable.saveMenuOrder');
    // 定制菜单,资源路由
    Route::resource('menutable', 'MenuTableController');
    // 图标参考
    Route::get('icon', 'IndexController@icon')->name('icon.index');
    // ajax获取用户列表
    Route::post('get_users', 'UserController@getUsers')->name('user.getUsers');
    // 用户,资源路由
    Route::resource('user', 'UserController');
    // 用户组,资源路由
    Route::resource('role', 'RoleController');
    // ajax获取权限列表
    Route::post('get_permissions', 'PermissionController@getPermissions')->name('permissions.getPermissions');
    // 权限,资源路由
    Route::resource('permissions', 'PermissionController');
    // 博客路由
    Route::post('article/get_articles', 'ArticleController@getArticles')->name('article.getArticles');
    Route::post('article/upload_image', "ArticleController@uploadImage")->name('article.uploadImage');
    Route::resource('article', 'ArticleController');
    // 博客文章分类
    Route::post('article_categories/save_order', 'ArticleCategoriesController@saveOrder')->name('article_categories.saveCateOrder');
    Route::resource('article_categories', 'ArticleCategoriesController');
    // 博客标签路由
    Route::post('article_tag/get_tags', 'ArticleTagController@getTags')->name('article_tag.getTags');
    Route::resource('article_tag', 'ArticleTagController');
    // 图片管理
    Route::get('picture', 'PictureController@index')->name('picture.index');
    Route::match(['get', 'post'], 'picture/upload', 'PictureController@uploadImage')->name('picture.upload');
    Route::delete('picture/{id}', 'PictureController@destroy')->name('picture.destroy');
    Route::post('picture/{id}/edit', 'PictureController@editFilename')->name('picture.edit');
    // 日志路由
    Route::get('log', 'LogViewerController@index')->name('log.index');
    Route::get('log/list', 'LogViewerController@listLogs')->name('log.list');
    Route::delete('log/delete', 'LogViewerController@delete')->name('log.destroy');
    Route::get('log/{date}', 'LogViewerController@show')->name('log.show');
    Route::get('log/{date}/download', 'LogViewerController@download')->name('log.download');
    Route::get('log/{date}/{level}', 'LogViewerController@showByLevel')->name('log.filter');
    // 系统设置
    Route::get('setting/{mode?}', 'SettingController@index')->name('setting.index');
    Route::put('setting/{id}', 'SettingController@saveSet')->name('setting.update');
});

//
Route::group(['prefix' => 'member', 'namespace' => 'Member', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return redirect('member/index');
    });
    // 会员中心
    Route::get('index', 'MemberController@index')->name('member.index');
    // 资料编辑
    Route::get('edit', 'MemberController@edit')->name('member.edit');
    // 资料编辑保存
    Route::post('edit', 'MemberController@editStore')->name('member.edit');
    // 重置密码
    Route::get('password', 'MemberController@password')->name('member.password');
    // 重置密码保存
    Route::post('password', 'MemberController@passwordStore')->name('member.password');
});

app/Models/User.php
<?php

namespace App\Models;

use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable implements Transformable
{
    use TransformableTrait;

    use Notifiable;

    //用户组权限验证
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use DataTables;
use App\Models\Role;
use App\Repositories\Eloquent\UserRepositoryEloquent;
use App\Models\User;

class UserController extends Controller
{
    protected $userRepositoryEloquent;

    public function __construct(UserRepositoryEloquent $userRepositoryEloquent)
    {
        $this->userRepositoryEloquent = $userRepositoryEloquent;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.user_list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userRepositoryEloquent->find($id);
        // 查询用户组
        $roles = Role::all();

        $data = [
            'roles' => $roles,
            'user' => $user,
        ];
        return view('admin.user.user_edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result = $this->userRepositoryEloquent->editUserRole($id, $request->role_id);
        if ($result) {
            return redirect()->route('user.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->userRepositoryEloquent->find($id);
        if ($user->hasRole('admin')) {
            return response()->json(['code' => 1, 'error' => '删除管理员？搞事情？'], 422);
        }
        if ($user->id == \Auth::id()){
            return response()->json(['code' => 1, 'error' => '不允许删除自己？搞事情？'], 422);
        }
        $user->delete();
        return response()->json(['code' => 0, 'message' => 'success']);
    }

    /**
     * ajax获取权限列表数据
     * */
    public function getUsers()
    {
        $users = User::query();
        $datatables_json = DataTables::of($users)
            ->addColumn('action', function ($user){
            $edit_url = route('user.edit', $user->id);
            $delete_url = route('user.destroy', $user->id);
            return <<<Eof
                <a href="javascript:;" class="btn btn-outline dark btn-sm black mt-sweetalert"
                                                            style="margin-bottom: 0;"
                                                           data-title="确定要删除该用户吗？"
                                                           data-message="（该用户的所有数据会被删除）"
                                                           data-type="warning"
                                                           data-allow-outside-click="true"
                                                           data-show-cancel-button="true"
                                                           data-cancel-button-text="点错了"
                                                           data-cancel-button-class="btn-danger"
                                                           data-show-confirm-button="true"
                                                           data-confirm-button-text="确定"
                                                           data-confirm-button-class="btn-info"
                                                           data-popup-title-success="删除成功"
                                                           data-close-on-cancel="true"
                                                           data-close-on-confirm="false"
                                                           data-show-loader-on-confirm="true"
                                                           data-ajax-url="{$delete_url}"
                                                           data-remove-dom="user_li_"
                                                           data-id="{$user->id}"
                                                        >
                                                            <i class="fa fa-trash-o"></i>
                                                            删除
                                                        </a>
                                                        <a href="{$edit_url}" class="btn btn-outline green btn-sm purple"><i class="fa fa-edit"></i>编辑</a>
Eof;
        })
            ->addColumn('name', function ($user) {
                return htmlspecialchars($user->name);
            })
            ->addColumn('email', function ($user) {
                return htmlspecialchars($user->email);
            })
            ->addColumn('role', function ($user) {
                $roles = '';
                if(!empty($user->roles)) {
                    foreach($user->roles as $role) {
                        $roles .= htmlspecialchars($role->display_name).'&nbsp;';
                    }
                } else {
                    $roles =  '无角色';
                }
                return '<span class="label label-sm label-success">' . $roles . '</span>';
            })
            ->rawColumns(['role', 'action'])
            ->setRowId(function ($user) {
                return 'user_li_'.$user->id;
            })
            ->make();

        return $datatables_json;
    }
}

resources/views/admin/user/user_edit.blade.php
@extends('admin.layouts.main')

{{--顶部前端资源--}}
@section('styles')

@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6 ">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-red-sunglo">
                        <i class="icon-settings font-red-sunglo"></i>
                        <span class="caption-subject bold uppercase"> 编辑用户资料 </span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form role="form" lpformnum="1" _lpchecked="1" method="post" action="{{ route('user.update', [$user->id]) }}">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="form-body">
                            <div class="form-group">
                                <label>用户名</label>
                                <input type="text" class="form-control" placeholder="Disabled" disabled="" value="{{ $user->name }}">
                            </div>
                            <div class="form-group">
                                <label>邮箱</label>
                                <input type="text" class="form-control" placeholder="Readonly" readonly="" value="{{ $user->email }}">
                            </div>
                            <div class="form-group">
                                <label>用户组</label>
                                <select class="form-control" name="role_id">
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}" @if($user->hasRole($role->name)) selected @endif @if($user->id == 1) disabled @endif>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>加入时间</label>
                                <input type="text" class="form-control" placeholder="Disabled" disabled="" value="{{ $user->created_at }}">
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">提交</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')

@endsection

resources/views/admin/user/user_list.blade.php
@extends('admin.layouts.main')

{{--顶部前端资源--}}
@section('styles')

@endsection

{{--页面内容--}}
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-red"></i>
                        <span class="caption-subject font-red sbold uppercase">用户管理</span>
                    </div>
                   {{-- <div class="actions">
                        <div class="btn-group">
                            <a href="{{ route('user.create') }}" class="btn green btn-outline">
                                <i class="fa fa-edit"></i>
                                添加权限
                            </a>
                        </div>
                    </div>--}}
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                            <thead>
                            <tr role="row" class="heading">
                                <th > ID </th>
                                <th > 用户名 </th>
                                <th > 邮箱 </th>
                                <th > 角色 </th>
                                <th > 注册时间 </th>
                                <th > 最后登录 </th>
                                <th > 操作 </th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection

{{--尾部前端资源--}}
@section('script')
<script type="text/javascript">
    var ajax_url = "{{ route('user.getUsers') }}";
</script>
<script src="{{asset('assets/admin/layouts/scripts/datatable.js')}}" type="text/javascript"></script>
<script src="{{asset('vendor/datatables/datatables.min.js')}}" type="text/javascript"></script>
<script src="{{asset('vendor/datatables/plugins/bootstrap/datatables.bootstrap.js')}}" type="text/javascript"></script>
{{--ajax使用--}}
<script src="{{asset('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
{{--datatables操作插件--}}
<script src="{{asset('assets/admin/user/scripts/datatables-users.js')}}" type="text/javascript"></script>
{{--sweetalert弹窗--}}
<script src="{{asset('assets/admin/layouts/scripts/sweetalert/sweetalert-ajax-delete.js')}}" type="text/javascript"></script>

@endsection